apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: udaconnect-ingress
  # annotations:
  #   cert-manager.io/cluster-issuer: <%= issuer_provider %>-<%= cluster_name %>
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: "udaconnect.10.0.0.47.sslip.io"
      http:
        paths:
          - pathType: Prefix
            path: /udaconnect(/api/persons/\d*/connection/?)
            backend:
              service: 
                name: udaconnect-connection-api
                port:
                  number: 5000
          - pathType: Prefix
            path: /udaconnect(/api/persons/\d*/?)
            backend:
              service: 
                name: udaconnect-api
                port:
                  number: 5000
          - pathType: Prefix
            path: /udaconnect(/api/locations/\d*/?)
            backend:
              service: 
                name: udaconnect-api
                port:
                  number: 5000
          - pathType: Prefix
            path: /udaconnect(/api/persons/?)
            backend:
              service: 
                name: udaconnect-api
                port:
                  number: 5000
          - pathType: Prefix
            path: /udaconnect(/api/locations/?)
            backend:
              service: 
                name: udaconnect-api
                port:
                  number: 5000
          - pathType: Prefix
            path: /udaconnect/(.*)
            backend:
              service: 
                name: udaconnect-app
                port:
                  number: 3000
